import Head from "next/head";
import { ReactElement } from "react";
import { NextPageWithLayout, IActivity } from "@app-types";
import { MainLayout } from "layouts/main-layout";
import { GetServerSideProps } from "next";
import { ActivityCard } from "widgets/activity-card";

interface PageProps {
  activity: IActivity;
}

export const getServerSideProps: GetServerSideProps<{
  activity: IActivity;
}> = async context => {
  const { activityId } = context.query;

  const res = await fetch(`http://localhost:5000/activities/${activityId}`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
  const data = (await res.json()) as { data: IActivity };

  return {
    props: { activity: data.data },
  };
};

const Page: NextPageWithLayout<PageProps> = ({ activity }) => {
  return (
    <>
      <Head>
        <title>Activity | Daiko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ActivityCard activity={activity} full />
    </>
  );
};

Page.getLayout = (page: ReactElement) => {
  return <MainLayout title="Activity">{page}</MainLayout>;
};

export default Page;
