import Head from "next/head";
import { ReactElement, useEffect } from "react";
import { NextPageWithLayout, IUser, IActivity } from "types/types";
import { MainLayout } from "layouts/MainLayout";
import { GetServerSideProps } from "next";
import { api } from "lib/ky/options";
import { ActivityCard } from "widgets/ActivityCard";
import { useSession } from "next-auth/react";

interface PageProps {
  activities: IActivity[];
}

export const getServerSideProps: GetServerSideProps<{
  activities: IActivity[];
}> = async context => {
  const res = await fetch("http://localhost:5000/activities", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
  const data = (await res.json()) as { data: IActivity[] };

  return {
    props: { activities: data.data },
  };
};

const Page: NextPageWithLayout<PageProps> = ({ activities }) => {
  return (
    <>
      <Head>
        <title>Activities | Daiko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {activities &&
        activities.map(activity => {
          return <ActivityCard key={activity._id} activity={activity} />;
        })}
    </>
  );
};

Page.getLayout = (page: ReactElement) => {
  return <MainLayout title="Activities">{page}</MainLayout>;
};

export default Page;
