import Head from "next/head";
import { GetServerSideProps } from "next";
import { ReactElement } from "react";
import { IUser, NextPageWithLayout } from "@app-types";
import { MainLayout } from "layouts/main-layout";
import { getServerUser } from "@modules/authentication";
import { TRequestType } from "@app-types";
import { checkAuthMiddleware } from "@modules/authentication";

export const getServerSideProps: GetServerSideProps<{}> = checkAuthMiddleware(
  async (context, user) => {
    return { props: {} };
  },
);

interface PageProps {
  posts: { title: string; body: string; id: string }[];
}

const Page: NextPageWithLayout<PageProps> = () => {
  return (
    <>
      <Head>
        <title>Daiko | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

Page.getLayout = (page: ReactElement) => {
  return <MainLayout title="Home">{page}</MainLayout>;
};

export default Page;
