import * as S from "screens/signin/styles";
import { useEffect, useState } from "react";
import { NextPageWithLayout } from "@app-types";
import { FcGoogle } from "react-icons/fc";
import {
  InputLabel,
  FormControl,
  Button,
  InputAdornment,
  IconButton,
  OutlinedInput,
  FormHelperText,
} from "@mui/material";
import { Visibility, VisibilityOff } from "@mui/icons-material";
import { useFormik } from "formik";
import * as Yup from "yup";
import Link from "next/link";
import { useRouter } from "next/router";
import { GetServerSideProps } from "next";
import { toast } from "react-hot-toast";
import { preventAuthUsersMiddleware } from "@modules/authentication";
import { useAuth, AuthStatus } from "core/modules/authentication";
import Head from "next/head";

const SigninSchema = Yup.object().shape({
  email: Yup.string().email("Invalid email").required("Email required"),
  password: Yup.string().required("Password required"),
});

export const getServerSideProps: GetServerSideProps<{}> =
  preventAuthUsersMiddleware(async context => {
    return {
      props: {},
    };
  });

interface PageProps {}

const Page: NextPageWithLayout<PageProps> = ({}) => {
  const router = useRouter();
  const { signIn, session } = useAuth();

  const { error } = router.query;
  useEffect(() => {
    if (error) {
      toast.error(error as string);
    }
  }, [error]);

  if (session.status === AuthStatus.Authenticated) {
    router.push(`/${session.user?._id}`);
  }

  const handleGoogleSignIn = async () => {
    router.push("http://localhost:5000/signin/google");
  };

  const formik = useFormik({
    initialValues: {
      email: "",
      password: "",
    },
    onSubmit: async ({ email, password }) => {
      signIn({
        email,
        password,
      });
    },
    validationSchema: SigninSchema,
  });

  const [passwordShown, setPasswordShown] = useState(false);

  return (
    <>
      <Head>
        <title>Sign in | Daiko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Container>
        <S.Title>Sign In</S.Title>
        <S.Form onSubmit={formik.handleSubmit}>
          <FormControl error={formik.touched.email && !!formik.errors.email}>
            <InputLabel htmlFor="email">Email</InputLabel>
            <OutlinedInput
              id="email"
              label="Email"
              {...formik.getFieldProps("email")}
            />
            {formik.touched.email && !!formik.errors.email && (
              <FormHelperText>{formik.errors.email}</FormHelperText>
            )}
          </FormControl>

          <FormControl
            error={formik.touched.password && !!formik.errors.password}
          >
            <InputLabel htmlFor="password">Password</InputLabel>
            <OutlinedInput
              label="Password"
              id="password"
              {...formik.getFieldProps("password")}
              type={passwordShown ? "type" : "password"}
              endAdornment={
                <InputAdornment position="end">
                  <IconButton
                    aria-label="toggle password visibility"
                    onClick={() => {
                      setPasswordShown(prev => !prev);
                    }}
                    edge="end"
                  >
                    {passwordShown ? <VisibilityOff /> : <Visibility />}
                  </IconButton>
                </InputAdornment>
              }
            />
            {formik.touched.password && !!formik.errors.password && (
              <FormHelperText>{formik.errors.password}</FormHelperText>
            )}
          </FormControl>

          <Button variant="contained" type="submit">
            Sign in
          </Button>
        </S.Form>
        <Button
          fullWidth
          variant="outlined"
          onClick={handleGoogleSignIn}
          sx={{ gap: "20px" }}
        >
          <FcGoogle size={20} /> Sign in with Google
        </Button>

        <Link href="/signup">
          Haven`t registered yet? <strong>Create an account</strong>
        </Link>
      </S.Container>
    </>
  );
};

export default Page;
