import { GetServerSideProps } from "next";
import { ReactElement } from "react";
import { MainLayout } from "layouts/main-layout";
import { NextPageWithLayout } from "@app-types";
import { AccountLinkingSection } from "widgets/account-linking-section";
import { SettingPasswordSection } from "widgets/setting-password-section";
import Head from "next/head";
import { checkAuthMiddleware } from "@modules/authentication";

export const getServerSideProps: GetServerSideProps<{}> = checkAuthMiddleware(
  async (context, user) => {
    return { props: {} };
  },
);

interface PageProps {}

const Page: NextPageWithLayout<PageProps> = ({}) => {
  return (
    <>
      <Head>
        <title>Account settings | Daiko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AccountLinkingSection />
      <SettingPasswordSection />
    </>
  );
};

Page.getLayout = (page: ReactElement) => {
  return <MainLayout title="Settings">{page}</MainLayout>;
};

export default Page;
