import Head from "next/head";
import { ReactElement, useEffect } from "react";
import { NextPageWithLayout } from "types/types";
import { GetServerSideProps } from "next";
import axios from "axios";
import { LizaLoader } from "shared/LizaLoader";
import { useRouter } from "next/router";
import * as S from "styles/pages-styles/auth-callback/styles";
import { toast } from "react-hot-toast";

interface PageProps {}

// export const getServerSideProps: GetServerSideProps<{}> = async context => {
//   return {};
// };

const Page: NextPageWithLayout<PageProps> = ({}) => {
  const router = useRouter();

  useEffect(() => {
    if (router.query.code) {
      (async () => {
        const result = await axios.get(
          `http://localhost:5000/auth/token?code=${router.query.code}`,
          { withCredentials: true },
        );

        if (result.data.success) {
          toast.success("Signing in successfully");
          router.replace("/");
        } else {
          toast.error("Signing in failed, try again");
          router.replace("/login");
        }
      })();
    }
  }, [router.query.code]);

  return (
    <>
      <Head>
        <title>Charity | Daiko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Main>
        <LizaLoader width={150} height={150} />
      </S.Main>
    </>
  );
};

export default Page;
