import Head from "next/head";
import { useEffect } from "react";
import { NextPageWithLayout } from "@app-types";
import { GetServerSideProps } from "next";
import { LizaLoader } from "shared/liza-loader";
import { useRouter } from "next/router";
import * as S from "screens/callback-link/styles";
import { toast } from "react-hot-toast";
import { api } from "@modules/axios";
import { preventAuthUsersMiddleware } from "@modules/authentication";

export const getServerSideProps: GetServerSideProps<{}> =
  preventAuthUsersMiddleware(async context => {
    if (!context.query?.code) {
      return {
        redirect: {
          destination: "/activity",
          permanent: false,
        },
      };
    }

    return { props: {} };
  });

interface PageProps {}

const Page: NextPageWithLayout<PageProps> = ({}) => {
  const router = useRouter();

  useEffect(() => {
    if (router.query.code) {
      (async () => {
        const result = await api.patch(
          `/accounts/${router.query.code}`,
          {},
          { withCredentials: true },
        );

        if (result.data) {
          toast.success("Linked account successfully");
        } else {
          toast.error("Linking account failed, try again");
        }
        router.replace("/account/settings");
      })();
    }
  }, [router.query.code]);

  return (
    <>
      <Head>
        <title>Charity | Daiko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Main>
        <LizaLoader width={150} height={150} />
      </S.Main>
    </>
  );
};

export default Page;
