import Head from "next/head";
import { ReactElement } from "react";
import { NextPageWithLayout } from "@app-types";
import { MainLayout } from "layouts/main-layout";

interface PageProps {}

const Page: NextPageWithLayout<PageProps> = ({}) => {
  return (
    <>
      <Head>
        <title>Charity | Daiko</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </>
  );
};

Page.getLayout = (page: ReactElement) => {
  return <MainLayout title="Charity">{page}</MainLayout>;
};

export default Page;
